---
- name: Configure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    mode: 0644
    dest: /etc/filebeat/filebeat.yml
  notify: restart Filebeat
- name: Set Filebeat systemwork
  become: true
  ansible.builtin.shell: filebeat modules enable system
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'
- name: Load Kibana dashboard
  become: true
  ansible.builtin.shell: filebeat setup
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded
  notify: restart Filebeat
  