---
- name: Configure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    mode: 0644
    dest: /etc/filebeat/filebeat.yml
  notify: restart Filebeat
- name: Set Filebeat systemwork
  become: true
  ansible.builtin.shell: filebeat modules enable system
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'
- name: Setup pipeline module for Logstash
  become: true
  ansible.builtin.shell: filebeat setup --pipelines --modules system
#- name: Load Elasticsearch index template
#  become: true
#  ansible.builtin.shell: filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["http://{{ hostvars['el-instance']['ansible_facts']['default_ipv4']['address'] | default('0.0.0.0') }}:9200"]'
#- name: Load Kibana dashboard
#  become: true
#  ansible.builtin.shell: filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['http://{{ hostvars['el-instance']['ansible_facts']['default_ipv4']['address'] | default('0.0.0.0') }}:9200'] -E setup.kibana.host=http://{{ hostvars['k-instance']['ansible_facts']['default_ipv4']['address'] | default('0.0.0.0') }}:5601
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded
  notify: restart Filebeat
  
