---
- name: Converge
  hosts: all
  tasks:
    - name: "Include elastic-role"
      include_role:
        name: "elastic"
    - name: "Include kibana-role"
      include_role:
        name: "kibana_role"
    - name: "Include logstash-role"
      include_role:
        name: "logstash_role"
    - name: "Include filebeat-role"
      include_role:
        name: "filebeat-role"


